latchset/tang

tests/adv, tests/rec
When /usr/lib/systemd/systemd-activate does not exist but
/lib/systemd/systemd-activate does.
Signed-off-by: Loic Dachary <loic@dachary.org>
=> tests: support /lib/systemd/systemd-activate

README.md
It took a little while get the right packages installed to build tang on Fedora. This adds the package names so other won't have to search for the proper packages when building.
=> doc: Added Fedora package names

README.md, units/tangd.xinetd
Add an example configuration file for xinetd daemon.
Alter README.md to highlight that Tang can be run on
small devices such as Wi-Fi routers running Openwrt
using xinetd for socket activation.
Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>
=> Let world know how lightweight Tang really is

README.md
The dockerfile seems to have moved from github to gitlab. I don't know the old Dockerfile, but it is the same user, so probably it is the same repository.
=> Fix dockerfile link

meson.build
When using `meson --buildtype=plain` (e.g. for packaging), compilation fails with
```
cc1: error: ‘-Wformat-security’ ignored without ‘-Wformat’ [-Werror=format-security]
cc1: all warnings being treated as errors
```
Add `-Wformat` to make `-Wformat-security` work even when not using the default meson warning configuration.
=> Use -Wformat in addition to -Wformat-security in add_project_arguments

units/tangd.socket, units/tangd@.service.in
This commit fixes the following ordering cycle found on Fedora 30+ and RHEL 8.1:
~~~
systemd[1]: sockets.target: Found ordering cycle on tangd.socket/start
systemd[1]: sockets.target: Found dependency on tangd-keygen.service/start
systemd[1]: sockets.target: Found dependency on basic.target/start
systemd[1]: sockets.target: Found dependency on sockets.target/start
systemd[1]: sockets.target: Job tangd.socket/start deleted to break ordering cycle starting with sockets.target/start
[ SKIP ] Ordering cycle found, skipping Tang Server socket
~~~
This is tracked by Red Hat through [BZ #1792173](https://bugzilla.redhat.com/show_bug.cgi?id=1792173)
The previous implementation of the Tang socket was making it depend on services, which is not how sockets are expected to be configured. …
=> Fixed Ordering cycle found, causing spurious issues during boot (no tangd.socket enabled, or no network, etc.)

src/keys.c
Follow-up from 60905058, where we added functions for key manipulation.
=> keys: return NULL if jose_jwk_pub() fails

src/tangd.c
When an HTTP parser error happens, tangd is currently exiting with an
error status, which may cause trouble in some scenarios [1].
However, we don't exit with an error in situations where we try requests
that do not exist, for instance. It makes sense to only exit with an
error when the error was with tangd itself, e.g.: when we are unable to
read the directory with the keys, not when the actual HTTP operation
does not succeed for some reason.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1828558
=> Exit with success unless the issue was with with tangd itself

src/tang-show-keys, src/tangd-keygen, tests/adv
From release 18, clevis changed to use SHA-256 as the default hash for
the JWK thumbprints. Let's update tang-show-keys and tangd-keygen to
also do that.
=> tang-show-keys and tangd-keygen now use SHA-256 for the thumbprints

src/meson.build, src/tangd-rotate-keys
So that it becomes simpler to perform key rotation on the server side.
Usage: tangd-rotate-keys [-h] [-v] -d <KEYDIR>
Example:
$ sudo tangd-rotate-keys -d /var/db/tang -v
Disabled advertisement of key 5AiUA4IhvOFdXzFavO78TKJ8hEsfGk8I6ymy4rBPWi8.jwk -> .5AiUA4IhvOFdXzFavO78TKJ8hEsfGk8I6ymy4rBPWi8.jwk
Disabled advertisement of key dDC74X-o31Fq5VJaM9iZ4baZD2hhHw-RrIMkxEz35Xc.jwk -> .dDC74X-o31Fq5VJaM9iZ4baZD2hhHw-RrIMkxEz35Xc.jwk
Created new key bIGVyIP2D_NJGQeFA9cf9oix5KEVQyVq9ZGjjv0s3D8.jwk
Created new key BL4IR73UhG8yyYbvGJspPIlLvG6AzTnM850tlCKrcII.jwk
Keys rotated successfully
=> Add tangd-rotate-keys helper script

.github/workflows/build.yml
Test was always showing as suceeding due to a faulty logic.
=> Fix failing logic in CI

.github/workflows/build.yml
So that the CI will not stop if either of these fail.
=> ci: mark fedora:rawhide and ubuntu:devel as unstable

meson.build, meson_options.txt, src/meson.build, src/tangd-keygen.in, src/tangd-rotate-keys.in, units/tangd@.service.in
So that we can run tang itself with a different user.
Systemd unit and helpers for rotating keys updated to use the
new user and group.
=> Specify user and group for tang

src/keys.c
returned.
This allows for file I/O issues as well as JSON parsing issues to be reported.
=> When json_load_file fails report the error details information

units/meson.build, units/tangd.socket.in
On OSTree-enabled systems (such as Fedora CoreOS), every update recreates the passwd and group files, which means that the dynamically-assigned ID and GID of the tang daemon may change, depending on the order of createuser calls. This patch ensures that starting the socket unit will fix any ownership issues in the jwkdir.
This is essentially moving the [Fedora %post script](https://src.fedoraproject.org/rpms/tang/blob/ba7119863624a55ac4bf79e19acd2a26350896e0/f/tang.spec#_68) out of RPM and into the systemd unit instead.
=> tangd.socket: Set ownership and mode of jwkdir

src/socket.c
The issue being handled is explained in this issue: #109
=> use sigaction instead of signal for SIGCHLD processing

meson.build
Change meson.build to include new release, that will contain latest fixes in tang repository
Resolves: #112
Proposed changelog:
* Add v2 version for codecov action (#1fcfdb6)
* socket: fix possible buffer overflow in listen_port() (#9b9d149)
* socket: free socket list before exiting (#5631569)
* tests: make sure on_exit handler completes (#0cacc91)
* tests: fix wait_for_port() retry mechanism (#5160a4a)
* use sigaction instead of signal for SIGCHLD processing (#f44f4ec)
* tangd.socket: Set ownership and mode of jwkdir (#ae736c9)
=> Create new release (version 13)

src/keys.c, src/tangd-keygen.in, src/tangd-rotate-keys.in
When we create/rotate keys using either the tangd-keygen and tangd-rotate-keys helpers, there is a small window between the keys being created and then the proper ownership permissions being set. This also happens when there are no keys and tang creates a pair of keys itself.
In certain situations, such as the keys directory having wide open permissions, a user with local access could exploit this race condition and read the keys before they are set to more restrictive permissions.
To prevent this issue, we now set the default umask to 0337 before creating the files, so that they are already created with restrictive permissions; afterwards, we set the proper ownership as usual.
Issue reported by Brian McDermott of CENSUS labs.
Fixes CVE-2023-1672
Reviewed-by: Sergio Arroutbi …
=> Fix race condition when creating/rotating keys

.github/workflows/install-dependencies, meson.build, src/http.c, src/http.h, src/tangd.c
As http-parser has been unmaintained for a while [1], let's add support for its natural replacement, llhttp.
However, as llhttp does not seem to be packaged in distros like Debian [2], we will keep supporting building with http-parser for time being, preferring llhttp, if it is present.
Resolves: #64 
[1] https://github.com/nodejs/http-parser/issues/522
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977716
=> Add support for building with llhttp instead of http-parser

.github/workflows/build.yml, .github/workflows/coverage.yml, .github/workflows/install-dependencies
Make sure man page build gets tested on all builds by adding asciidoc to dependencies and update meson command to avoid a meson warning.
=> Build tweaks

doc/tang.8.adoc, src/tang-show-keys, src/tangd.c, tests/adv, tests/adv-socat-endpoint, tests/adv-standalone-endpoint, tests/helpers, tests/meson.build, tests/rec, tests/rec-socat-endpoint, tests/rec-standalone-endpoint
=> Include parameter to indicate endpoint

src/http.h, src/tangd.c
http_parser_execute() returns the number of parsed bytes, while llhttp_execute() returns an error code.
=> Fix issue introduced in http-parser -> llhttp conversion

.github/workflows/build.yml, .github/workflows/coverage.yml
Updating to Node20 involves removal of a pair of distributions for compilation:
- Ubuntu Bionic (End of Life Date was 31 May 2023)
- Centos7 (End of Life Date for 30 Jun 2024)
Resolves: #141
=> Upgrade checkout Github action (v3->v4)

src/socket.c
This memory leak, although not easily reproducible, has been detected by Static Application Security Testing tool. This fix eliminates it.
=> Fix memory leak reported by clang tool
